chore: updating dependabot to support gha, python, docker and dev container
rajpalc7/indy-plenum pull request #1
Opened 2024-05-03 18:28 UTC by rajpalc7

2024-05-03 18:28 UTC, rajpalc7 commented
Hi @wadeBarnes, this is ready for review.

2024-05-06 13:50 UTC, WadeBarnes requested changes
@rajpalc7, You are missing at least one Docker file.

2024-05-06 17:35 UTC, rajpalc7 commented
Hi @WadeBarnes, missing docker file has been added now.

2024-05-06 19:14 UTC, WadeBarnes approved these changes

2024-05-16 21:05 UTC, closed without merging